# Generated by Django 2.2.17 on 2020-12-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bokete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bokete.Question', verbose_name='question'),
        ),
    ]
