# Generated by Django 2.2.17 on 2020-12-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bokete', '0002_image_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bokete.Question', verbose_name='question'),
        ),
    ]
